### ISSUE TITLE
Build error !

### ISSUE THREAD

**Issue by LorediBega** [CuppaLabs/angular2-datetimepicker#1]
I got a build error when building in production mode (npm run build-prod) which says 
ERROR in node_modules\angular2-datetimepicker\datepicker.component.d.ts.DatePicker.html
Expected 1 arguments, but got 0

**Comment by CuppaLabs** [comment]
try with v1.0.1. Let me know if its working.

**Comment by LorediBega** [comment]
I'm using 3.10.8, i can't downgrade to 1.0.1. However seems that the problem is with this method generateYearList(param: string): void;
It is somewhere called without any argument. If i remove this parameter it builds successfully

**Comment by CuppaLabs** [comment]
there is no version with 3.10.8. Please refer to this package https://www.npmjs.com/package/angular2-datetimepicker. The latest version is 1.0.1. The param issue is fixed there.

**Comment by LorediBega** [comment]
Sorry thought you were asking about angular CLI, how can i check the package version ?
I think that i'm using that version I've installed it yesterday and on package.json it displays as "ng-pick-datetime": "^5.0.0-beta.12",

**Comment by CuppaLabs** [comment]
https://www.npmjs.com/package/angular2-datetimepicker. Refer this link. It has all details.

**Comment by LorediBega** [comment]
I refered to this link yesterday when i installed it but it has installed the 1.0.0 version. I're installed now again and is ok . Thank you
