### ISSUE TITLE
 throws error : on page load on angular 4 

### ISSUE THREAD

**Issue by saravananNV** [CuppaLabs/angular2-datetimepicker#2]
Implemented Datetimepicker on angular 4 application throws error on page load "TypeError: Cannot read property 'getMonth' of undefined "

**Comment by markjritchie** [comment]
I'm getting the same problem. I trying to use it in a reactive form. You might also want to show some example code using it in a reactive form

**Comment by CuppaLabs** [comment]
please refer to example at https://cuppalabs.github.io/angular2-datetimepicker/#/datetimepicker

**Comment by aylmercarson** [comment]
same issue. it only seems to work if i invoke it via a template, and not with a templateurl

**Comment by CuppaLabs** [comment]
Tested in local. It works as expected. Please check your application code . Hence closing.

**Comment by aylmercarson** [comment]
wrapping this in a form tag appears to break it
